services:

  mongodb:
    image: mongo:latest
    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    volumes:
      - ./data/mongo:/data/db

    healthcheck:
      test: ["CMD-SHELL", "mongosh -u \"$$MONGO_INITDB_ROOT_USERNAME\" -p \"$$MONGO_INITDB_ROOT_PASSWORD\" --authenticationDatabase admin --eval \"db.adminCommand({ping:1})\" --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - data-network


  minio:
    image: minio/minio:latest
    restart: unless-stopped

    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}

    command: server /data --console-address ":9001"

    volumes:
      - ./data/minio:/data

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - data-network


  nifi:
    image: apache/nifi:latest
    restart: unless-stopped

    ports:
      - "8443:8443"

    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: ${NIFI_USER}
      SINGLE_USER_CREDENTIALS_PASSWORD: ${NIFI_PASSWORD}

    volumes:
      - ./data/nifi:/opt/nifi/nifi-current/data
      - ./data/raw:/opt/nifi/input
      - ./scripts:/opt/nifi/custom-scripts

    networks:
      - data-network


networks:
  data-network:
    driver: bridge